databaseChangeLog:
  - changeSet:
      id: create-application_status_history
      author: Eugene
      changes:
        - createTable:
            tableName: application_status_history
            columns:
              - column:
                  name: application_id
                  type: bigint
              - column:
                  name: status_history_id
                  type: bigint